name: Test Trigger

on:
  push:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Debug info

        run: |


          echo "Workflow triggered!"


          echo "Event: ${{ github.event_name }}"


          echo "Ref: ${{ github.ref }}"


          echo "SHA: ${{ github.sha }}"
